// src/lib/home/titles.svelte
<h1>
  <span class="first-name">Kaleab</span> <abbr title="Serekebrhan">S.</abbr> Melkie
</h1>

<sub>
  Co-founder <abbr title="and">&amp;&amp;</abbr>
  <abbr title="Chief Executive Officer">CEO</abbr><abbr title="at">,</abbr>
  <a href="https://www.kelaltech.com/">Kelal Tech PLC</a>
</sub>

<style>
  h1 {
    display: block;

    margin: 0;
    padding: 32px 0 16px;

    font-size: 2em;
    text-align: center;

    color: rgba(0, 0, 0, 0.63);
  }

  .first-name {
    color: rgba(0, 0, 0, 1);
  }

  sub {
    display: block;

    font-size: 0.96em;
    font-weight: 100;
    text-align: center;

    color: rgba(0, 0, 0, 0.63);
  }
</style>

// src/components/titles/titles.tsx
import styles from './titles.module.scss'

type TitlesProps = unknown

const Titles: React.FC<TitlesProps> = () => {
  return (
    <>
      <h1 className={styles.title}>
        <span className={styles['first-name']}>Kaleab</span>{' '}
        <abbr title="Serekebrhan">S.</abbr> Melkie
      </h1>

      <sub className={styles.subtitle}>
        Co-founder <abbr title="and">&amp;&amp;</abbr>{' '}
        <abbr title="Chief Executive Officer">CEO</abbr>
        <abbr title="at">,</abbr>{' '}
        <a href="https://www.kelaltech.com/">Kelal Tech PLC</a>
      </sub>
    </>
  )
}

export default Titles
